from abc import ABC, abstractmethod
class Adapter(ABC):
    @abstractmethod
    def discover(self): ...
    @abstractmethod
    def inspect(self, candidate): ...
    @abstractmethod
    def acquire(self, candidate): ...
    @abstractmethod
    def extract_metadata(self, candidate): ...