import { Link, useParams } from "wouter";
import { ArrowLeft, Clock, Hash, HardDrive } from "lucide-react";
import { Badge, Card, CardContent, CardHeader, CardTitle, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/core";
import { lifecycleLabel, lifecycleVariant, useSource } from "@/lib/api";
import { ErrorMessage, LoadingRows } from "./home";
export default function SourceDetail() {
 const { id } = useParams<{ id: string }>(); const query = useSource(id);
 if (query.isLoading) return <div className="py-20 text-center text-muted-foreground">Loading live source record…</div>;
 if (query.isError) return <div className="space-y-4"><Link href="/sources" className="text-primary hover:underline">Return to catalog</Link><ErrorMessage error={query.error} retry={query.refetch} /></div>;
 const detail = query.data!; const source = detail.source;
 return <div className="space-y-8 animate-in fade-in duration-500 pb-12"><div className="flex items-center gap-4 text-sm text-muted-foreground"><Link href="/sources" className="hover:text-foreground flex items-center gap-1"><ArrowLeft className="w-4 h-4"/>Catalog</Link><span>/</span><span className="font-mono text-foreground">{source.source_id}</span></div>
 <div className="border-b border-border pb-6"><div className="flex items-center gap-3 mb-2"><h1 className="text-3xl font-serif">{source.title ?? "Untitled source"}</h1><Badge variant={lifecycleVariant(source.archive_status)}>{lifecycleLabel(source.archive_status)}</Badge></div><p className="text-muted-foreground">{[source.speaker ?? source.author, source.publisher, source.date].filter(Boolean).join(" • ") || "Metadata not supplied"}</p></div>
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="space-y-6"><Card><CardHeader><CardTitle className="text-base flex gap-2"><Hash className="w-4 h-4"/>Identity & provenance</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><Field label="Stable ID" value={source.source_id} mono/><Field label="Rights status" value={source.rights_status}/><Field label="SHA-256" value={source.sha256} mono/>{source.error_log && <Field label="Recorded error" value={source.error_log}/>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base flex gap-2"><HardDrive className="w-4 h-4"/>Safe catalog metadata</CardTitle></CardHeader><CardContent className="space-y-3 text-xs"><Field label="Source type" value={source.source_type}/><Field label="MIME type" value={source.mime_type}/><Field label="Platform" value={source.platform}/><Field label="Discovery URL" value={source.discovery_url} mono/><Field label="File size" value={source.file_size === null ? null : `${source.file_size.toLocaleString()} bytes`}/></CardContent></Card></div>
 <div className="lg:col-span-2"><Card><CardHeader className="border-b"><CardTitle className="text-base flex gap-2"><Clock className="w-4 h-4"/>Processing history</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Stage</TableHead><TableHead>Transition</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{detail.events.length ? detail.events.map(event => <TableRow key={event.id}><TableCell className="font-mono text-xs">{event.created_at}</TableCell><TableCell>{event.pipeline_stage}</TableCell><TableCell className="font-mono text-xs">{event.previous_state ? `${lifecycleLabel(event.previous_state)} → ${event.new_state ? lifecycleLabel(event.new_state) : "—"}` : "—"}</TableCell><TableCell><Badge variant={event.status === "error" ? "destructive" : "secondary"}>{event.status}</Badge><p className="text-xs text-muted-foreground mt-1">{event.message ?? event.error ?? ""}</p></TableCell></TableRow>) : <LoadingRows columns={4}/>}</TableBody></Table></CardContent></Card></div></div></div>;
}
function Field({ label, value, mono = false }: { label: string; value: string | null; mono?: boolean }) { return <div><p className="text-xs uppercase tracking-wider text-muted-foreground mb-1">{label}</p><p className={`${mono ? "font-mono text-xs break-all" : ""}`}>{value || "Not recorded"}</p></div>; }